# Generated by Django 5.0.2 on 2024-02-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='image1',
            field=models.ImageField(blank=True, default='Screenshot (3).png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='image2',
            field=models.ImageField(blank=True, default='Screenshot (3).png', null=True, upload_to=''),
        ),
    ]
