# Generated by Django 5.0.2 on 2024-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enter_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_interest', models.CharField(max_length=255)),
                ('skills', models.TextField()),
                ('experiences', models.TextField()),
                ('related_projects', models.TextField()),
            ],
        ),
    ]
